# Generated by Django 2.1.3 on 2019-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pound Sterling'), ('USD', 'US Dollars'), ('CAD', 'Canadian Dollars')], max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='paypalcurrency',
            field=models.CharField(choices=[('GBP', 'Pound Sterling'), ('USD', 'US Dollars'), ('CAD', 'Canadian Dollars')], default='GBP', max_length=8, verbose_name='Currency'),
        ),
    ]
