# Generated by Django 2.1.3 on 2019-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_GBP_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='donationemailsender',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Donation Email Sender'),
        ),
    ]
