# Generated by Django 2.1.3 on 2019-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_donation_email_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='addresscity',
            field=models.CharField(blank=True, max_length=128, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='addressstate',
            field=models.CharField(blank=True, max_length=128, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='addressstreet',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street & Number/Name'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='addresszip',
            field=models.CharField(blank=True, max_length=128, verbose_name='Post Code'),
        ),
    ]
